repos:
-    repo: https://github.com/pre-commit/mirrors-autopep8
     rev: ''
     hooks:
     - id: autopep8
-    repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v2.4.0
     hooks:
     - id: trailing-whitespace
     - id: check-merge-conflict
-    repo: local
     hooks:
     - id: pytesttest
       name: pytesttest
       entry: ./pre-commit.sh
       language: script
       always_run: true